Repository TeamMiso/Miso_Android, pull requests merged in 2023-12, with the labels that each got.

#126 (#43)debounce instant search
  presentation/src/main/java/com/example/miso/ui/main/component/search/SearchTextField.kt
  presentation/src/main/java/com/example/miso/ui/main/screen/SearchScreen.kt
Labels: refactoring

#131 🔀 :: (#129) - all recycling list
  data/src/main/java/com/example/data/remote/api/RecyclablesAPI.kt
  data/src/main/java/com/example/data/remote/datasource/recyclables/RecyclablesDatasource.kt
  data/src/main/java/com/example/data/remote/datasource/recyclables/RecyclablesDatasourceImpl.kt
  data/src/main/java/com/example/data/remote/dto/recyclables/response/RecyclablesListResponse.kt
  data/src/main/java/com/example/data/repository/RecyclablesRepositoryImpl.kt
  domain/src/main/java/com/example/domain/model/inquiry/response/InquiryListResponseModel.kt
  domain/src/main/java/com/example/domain/model/recyclables/response/RecyclablesListResponseModel.kt
  domain/src/main/java/com/example/domain/repository/RecyclablesRepository.kt
  domain/src/main/java/com/example/domain/usecase/recyclables/GetAllRecyclablesListUseCase.kt
  presentation/src/main/java/com/example/miso/viewmodel/RecyclablesViewModel.kt
Labels: enhancement

#133 🔀 :: (#132) - push notification
  build.gradle.kts
  buildSrc/src/main/java/Dependency.kt
  buildSrc/src/main/java/Versions.kt
  data/build.gradle.kts
  data/src/main/java/com/example/data/remote/dto/auth/request/AuthLogInRequest.kt
  data/src/main/java/com/example/data/repository/AuthRepositoryImpl.kt
  di/build.gradle.kts
  domain/build.gradle.kts
  domain/src/main/java/com/example/domain/model/auth/request/AuthLogInRequestModel.kt
  presentation/build.gradle.kts
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/example/miso/ui/log_in/LogInActivity.kt
  presentation/src/main/java/com/example/miso/ui/log_in/screen/LogInScreen.kt
  presentation/src/main/java/com/example/miso/ui/splash/SplashActivity.kt
  presentation/src/main/java/com/example/miso/ui/util/MisoNotification.kt
  presentation/src/main/java/com/example/miso/viewmodel/util/errorHandling.kt
  settings.gradle.kts
Labels: enhancement

#135 🔀:: (#134) inqury camera choice
  presentation/src/main/java/com/example/miso/ui/camera/component/CameraPreview.kt
  presentation/src/main/java/com/example/miso/ui/camera/screen/CameraScreen.kt
  presentation/src/main/java/com/example/miso/ui/component/bottomsheet/MisoBottomSheet.kt
  presentation/src/main/java/com/example/miso/ui/component/icon/MisoIcon.kt
  presentation/src/main/java/com/example/miso/ui/inquiry/component/MoveGalleryButton.kt
  presentation/src/main/java/com/example/miso/ui/inquiry/component/bottomsheet/SelectPhotoPathBottomSheet.kt
  presentation/src/main/java/com/example/miso/ui/inquiry/component/bottomsheet/SelectPhotoPathBottomSheetComponent.kt
  presentation/src/main/java/com/example/miso/ui/inquiry/screen/InquiryScreen.kt
  presentation/src/main/java/com/example/miso/ui/main/MainActivity.kt
  presentation/src/main/java/com/example/miso/viewmodel/CameraViewModel.kt
  presentation/src/main/res/drawable/ic_camera_bottm_sheet.xml
  presentation/src/main/res/drawable/ic_gallery_bottom_sheet.xml
Labels: feature
